@startuml example
start
if (Аккаунт клиента существует?) then (да)
    :Авторизация клиента на сайте;
else (нет)
    :Клиент регистрируется на сайте;
endif
:Система подтверждает учётные данные клиента;
:Клиент выбирает товары и добавляет их в корзину.;
:Клиент переходит к оформлению заказа, выбирает способ доставки и оплаты;
if (Товар есть в наличии в выбранном количестве?) then (Да)

else (Нет)
  :Уведомление клиента о недоступности товара;
  if (Выбрать альтернативный товар?) then (Да)
    :Выбрать альтернативный товар;
  else (Нет)
    :Удалить отсутствующий товар из заказа;
  endif
endif
fork
  :Клиент выбирает способ оплаты (кредитная карта, PayPal, банковский перевод и т. д.);
  :Система проверяет платёжные детали и производит транзакцию;
fork again
  :Система уведомляет склад о необходимости собрать заказ;
  :Сотрудники склада комплектуют заказ по списку;
end fork
if (Оплата прошла успшено и товар готов к отправке?) then (Да)
  :Генерируется счёт-фактура;
  :Отправляется уведомление клиенту о подтверждении заказа и статусе доставки;
  :Заказ переходит в статус «Отправлен»;
else (Нет)
  :Отправляется уведомление клиенту о проблеме с платежом;
  :Клиенту предлагается повторить попытку оплаты или изменить способ оплаты;
  if (Клиента устраивает решение?) then (Нет)
    :Заказ отменяется;
  else (Да)
    :Клиенту возвращаются средства (если были списаны);
  endif
endif
:Система обновляет статус заказа по мере его продвижения к доставке;
:Клиент получает уведомления о каждом изменении статуса (подтверждение, отправка, доставка);
stop
@enduml