@startuml Class diagram

class User {
    -userID: Integer
    -userLogin: String
    -Name: String
    -MidleName: String
    -Surname: String
    -BirthDate: Date
    -Address: String
    +getFullName(): String
    +getBirthDate(): Date
}

class Student{
    +isActiveStudent(student: Student): Boolean
}

class Instructor{
    -startDate: Date
    -endDate: Date
    -courses: List<Course>
    +isActiveInstructor(instructor: Instructor): Boolean
}

class Course{
    -courseID: Integer
    -courseTitle: String
    -instructor: List<Instructor>
    -materials: List<Material>
    -isActual: Boolean
    +getActualCourses(): List<Course>
}

class Enrollment{
    -enrollmentStartDate: Date
    -enrollmentEndDate: Date
    -enrollmentedStudent: <<reference>> Student
    -enrollmentCourse: <<reference>> Cource
    -isSuccess: Bollean
    +getActiveCourses(student: Student): List<Course>
    +getInstructorCourses(instructor: Instructor): List<Course>
}

class Material{
    -materialId: Integer
    -materialTitle: String
    -materialType: String
    -materialActualizationDate: Date
    +getCourseMaterials(course: Course): List<Material>
}

class PaymentProcessor{
    +makePayment(): Boolean
}

class Order {
    -orderId: Integer
    -orderDate: Data
    -orderStatus: String
    -items: List<item>
    +getOrderStatus(): String
}

class Item{
    -itemId: Integer
    -itemName: String
    -itemPrice: Double
}

User <|-- Student: Наследование (студент - подтип пользователя)
User <|-- Instructor: Наследование (преподаватель - подтип пользователя)
Student "1" -- "0..*" Enrollment: Студент зачисляется на курс (ассоциация, 0..*)
Enrollment "0..*" -- "1" Course: Зачисление происходит на конкретный курс (ассоциация, 0..*)
Course "*" o-- "1..*" Material: Курс состоит из материалов (композиция, 1..*)
User ..> PaymentProcessor: Пользователь инициирует платеж (зависимость)
PaymentProcessor <.. Order: Заказ использует процессор платежей (зависимость)
Order "1" *-- "1..*" Item: Заказ содержит элементы (композиция, 1..*)
User "1" -- "0..*" Order: Пользователи размещают заказы (ассоциация, 0..*) 

@enduml